// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuq6Gedk1SKd8wmaxfcTfWaiMdGDj5IKo',
    appId: '1:1063254236749:web:347a4be6e12c77fea2c604',
    messagingSenderId: '1063254236749',
    projectId: 'bigo-game',
    authDomain: 'bigo-game.firebaseapp.com',
    storageBucket: 'bigo-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAre-VVc7YXW86RviIJ4mxk54N6B65biCA',
    appId: '1:1063254236749:android:313f90ccf4ed98ffa2c604',
    messagingSenderId: '1063254236749',
    projectId: 'bigo-game',
    storageBucket: 'bigo-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcYscjfcRr3T1cyuhAGceFNWHy5wOjIM',
    appId: '1:1063254236749:ios:8eea97b228e0f1baa2c604',
    messagingSenderId: '1063254236749',
    projectId: 'bigo-game',
    storageBucket: 'bigo-game.appspot.com',
    iosBundleId: 'com.example.bigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNcYscjfcRr3T1cyuhAGceFNWHy5wOjIM',
    appId: '1:1063254236749:ios:b444f805a9351136a2c604',
    messagingSenderId: '1063254236749',
    projectId: 'bigo-game',
    storageBucket: 'bigo-game.appspot.com',
    iosBundleId: 'com.example.bigo.RunnerTests',
  );
}
